# Site settings
title: Neya Ramanan
email: nrama080@uottawa.ca
url: nrama080.github.io
description: "Hi there! My name is Neya Ramanan. I am going into my third year of Honours Biomedical Sciences at the University of Ottawa with Extended French. Welcome! Bonjour. Je m'appelle Neya Ramanan. J'entre dans ma troisième année de spécialisation en sciences biomédicales à l'Univesité d'Ottawa avec le français enrichi. Bienvenue!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: nrama080.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/neya-ramanan-045186145/

# Build settings
markdown: kramdown
permalink: pretty
